### ISSUE TITLE
Output via [downloads] Shortcode

### ISSUE THREAD

**Issue by spencerfinnell** [easydigitaldownloads/edd-featured-downloads#1]
Would make more sense (and be so much more compatible with themes) to output via the [downloads] shortcode. Add a new attribute like `featured=true` or `orderby=featured`

This way previously filtered shortcode attributes will be applied, the theme specific styles for download items will be applied, all other filters will exist, etc.

Implemented in the next version of Marketify so the standard `[downloads]` shortcode can be used and all proper styles/filters carried over: https://github.com/Astoundify/marketify/blob/release/2.0.0/inc/integrations/edd/class-edd-sorting.php#L53-L55

Thoughts?

**Comment by amdrew** [comment]
Embarrassed to comment 2 years later, but yes this need to happen. Looks like I made a note of it but never followed up: https://github.com/easydigitaldownloads/edd-featured-downloads/blob/master/edd-featured-downloads.php#L269

**Comment by amdrew** [comment]
Funny, I even wrote a blog post about it, using Featured Downloads as an example: https://amdrew.com/how-to-filter-shortcodes-in-wordpress-3-6/

**Comment by amdrew** [comment]
Done!
