### ISSUE TITLE
Update plugin author & URI

### ISSUE THREAD

**Issue by LisaCee** [easydigitaldownloads/edd-featured-downloads#14]
We need to update the plugin author to be Sandhills, link to the extension site ~and add the item ID to the EDD_License instantiation.~

**Comment by robincornett** [comment]
Just noting here that it doesn't look like this plugin currently uses `EDD_License` at all and appears to have no update mechanism in place?

**Comment by ashleyfae** [comment]
> Just noting here that it doesn't look like this plugin currently uses `EDD_License` at all and appears to have no update mechanism in place?

It's a free plugin, served via the .org repo so we don't need `EDD_License` here.

**Comment by robincornett** [comment]
Ah, I promise I searched for it but since the tested to version is 4.9, it doesn't show in search. We should make sure to update that to 5.6 as well.

**Comment by LisaCee** [comment]
PR #17
