### ISSUE TITLE
Undefined index: download_edit_nonce 

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-featured-downloads#4]
`Notice: Undefined index: download_edit_nonce in /Applications/MAMP/htdocs/edd/wp-content/plugins/edd-featured-downloads/edd-featured-downloads.php on line 155`

Appears to happen when saving any post type (Post, Page, Download... all the same error).

**Comment by zeromajstor** [comment]
yes also have this error? what is the fix for it?

**Comment by amdrew** [comment]
Oops, missed this. On it.

@zeromajstor What version of PHP, EDD, EDD Featured Downloads + WP do you have? When do you see the error - when you save a post/download/etc?

@SDavisMedia I can't replicate this, can you still replicate it?

**Comment by zeromajstor** [comment]
WP 4.8.1.,  PHP 5.6,   EDD 2.8.6,  EDD featured downloads 1.0.2, everything latest version. I see this in my error log file : PHP Notice:  Undefined index: download_edit_nonce in /wp-content/plugins/edd-featured-downloads/edd-featured-downloads.php on line 155

**Comment by amdrew** [comment]
Thanks @zeromajstor!

If you clear your logs, what exactly are you doing when the error appears? Are you saving a download, post or page? I can't seem to replicate the issue (not denying there is one though). I'll keep digging to see if I can replicate.

**Comment by zeromajstor** [comment]
not sure what I was doing, I looked in logs and I saw it there, if  it happens again I will let you know.

**Comment by amdrew** [comment]
Ok great, just wondering if it's perhaps an old error or not. Were the dates of the error recent?

**Comment by zeromajstor** [comment]
Its new 21-Sep-2017 09:02:00 UTC, had few of them order, dont know what happened.

**Comment by amdrew** [comment]
Ok thanks! Will keep digging

**Comment by zeromajstor** [comment]
I think its something related to marketify theme and their featured widget.

**Comment by zeromajstor** [comment]
yes its related to widget featured/popular of marketify theme

**Comment by amdrew** [comment]
@zeromajstor Awesome! Can you list some steps to replicate the error? I take it the featured widget needs to be dragged to the homepage section the theme includes? Are you saving a download when the error occurs... or?

Once replicated I'll see if it is something I can fix in the plugin, otherwise I can let Marketify know of the issue.

**Comment by zeromajstor** [comment]
I  think this happens sometimes when you click on featured/popular button on widget.

**Comment by Catapult-Themes** [comment]
This happens when you have WP_DEBUG set to true and you save or publish a post type other than a download.

One fix is to replace lines 147 - 149 of edd-featured-downloads.php with:

```
if ( 'download' != get_post_type( $post_id ) ) {
  return;
}
```

**Comment by amdrew** [comment]
Something cant be screwed on right, I had `WP_DEBUG` set to false the entire time (I always have it true for obvious reasons). Thanks for the reminder @Catapult-Themes.

This just needed an `isset()` check.
